language: node_js
node_js:
  - "12.4.0"
after_success:
  - git config --global user.name "Wuilliam Lacruz"
  - git config --global user.email "wuilliam321@gmail.com"
  - npm run build
  - npm run deploy
deploy:
  email: wuilliam321@gmail.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build/
  on:
    branch: master
