language: node_js
node_js:
  - "12.4.0"
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build
  - npm run deploy
deploy:
  email: wuilliam321@gmail.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  project: ./build/
  on:
    branch: master
