language: node_js
node_js:
  - "12.4.0"
before_script:
  - npm run test
  - npm run build
deploy:
  email: wuilliam321@gmail.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build
  on:
    branch: master
